name: Deploy backend to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      # Optionnel : ajoute ceci si tu utilises TypeScript ou un build
      # - name: Build backend (optional)
      #   working-directory: backend
      #   run: npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: bimastore-backend  # Remplace par le nom EXACT de ton App Service Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_BACKEND_PUBLISH_PROFILE }}
          package: ./backend
